travis: with G++ 4.8
resolve an error:
In file included from ../node-expat.cc:1:0:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler

this needed by node-expat, node-gyp depend on it.